name: Build, publish and run the application

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract Docker metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  run:
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Copy ssh private key and the known_hosts file
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo "$SERVER_KEY" > ~/.ssh/id_rsa_server
          echo "$SERVER_KNOWN_HOSTS" > ~/.ssh/known_hosts
          sudo chmod 600 ~/.ssh/id_rsa_server ~/.ssh/known_hosts
        env:
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
          SERVER_KNOWN_HOSTS: ${{ secrets.SERVER_KNOWN_HOSTS }}

      - name: Run container remotely
        shell: bash
        run: ssh -i ~/.ssh/id_rsa_server $SERVER_USERNAME@$SERVER_HOST 'bash -s' < ./scripts/run-container.sh
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
